# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
      
# Orchestrate or schedule a set of jobs
jobs:
  hello_world_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "testing failure"
      - run: cat acbc
      - run: echo "Roll back is running"|
          when on_fail
workflows:
  # Name the workflow "my_exos"
  my_exos:
    jobs:
      - hello_world_fail
